### ISSUE TITLE
session.nearby_users() may fail when iterating "schools", KeyError: id

### ISSUE THREAD

**Issue by RailKill** [charliewolf/pynder#163]
**Pynder Version:** 0.0.13

Iterating through session.nearby_users() may sometimes fail with KeyError: id, happens when data["schools"] do not have the ID attribute. user.py, line 27 does not expect a school object with no ID attribute.

**Comment by MichaelGofron** [comment]
Yeah I'm getting this same exception

**Comment by MichaelGofron** [comment]
It seems the issue is with installing pynder using pip. The pip version release seems to not have the latest build on github. You have to add a check on the id.

Something like this, worked for me. The release version should be updated though: 
            for school in data["schools"]:
                if ("id" in school):
                    self.schools_id.extend([school["id"]])

**Comment by NeoGeneration** [comment]
Where can I place the fix?

**Comment by henriqueluzz** [comment]
This is because your environment version of the Pynder library is not up to date with this repository.
I fixed that cloning this repository directly on my virtual environment site-packages folder which was:

/home/henrique/anaconda3/envs/tinderbot/lib/python3.6/site-packages/

**Comment by jasonminsookim** [comment]
I still can't get it to work after I copied over the library.

**Comment by RailKill** [comment]
@jasonminsookim 
Delete the Pynder library you currently have, then use pip to install it again by grabbing the latest build from GitHub like this:
```pip install git+https://github.com/charliewolf/pynder.git```

**Comment by RailKill** [comment]
PyPi has the old version of Pynder which is why some users experienced this problem. An issue has already been opened for that: https://github.com/charliewolf/pynder/issues/190

Therefore, closing this issue because the fix is already in the latest build.
